version: '3.7'

services:

  proyectoseg:
    environment:
      llave: ${LLAVE}
      bdBase: ${bdBase}  
      bdUser: ${bdUser}
      bdPass: ${bdPass}
      bdHost: ${bdHost}
      bdPort: ${bdPort}
    build: ./apli
    restart: always
    volumes:
      - ./apli/credentialmanager:/code
    depends_on:
      - based
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1024M"
      
      
  based:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${bdPass}
      MYSQL_DATABASE: 'cuentas'
      MYSQL_USER: 'root'
    volumes:
      - ./data:/var/lib/mysql

  
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./apli/credentialmanager/admincred/static:/static 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - proyectoseg
    ports:
      - 8000:80
      - 443:443
